spring.application.name=master_services
server.port=8080

# PostgreSQL Connection - Password tumhara wala daalo
spring.datasource.url=jdbc:postgresql://localhost:5432/iiiotwms
spring.datasource.username=postgres
spring.datasource.password=psd@1185
spring.datasource.driver-class-name=org.postgresql.Driver

# Table apne aap ban jayega
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true