spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:postgresql://localhost:5432/iiiotwms
    username: postgres
    password: psd@1185

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: psdixit85@gmail.com
    password: dtoo oyfj atpv hmxd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
        debug: true
    default-encoding: UTF-8
    test-connection: false
    from: ${spring.mail.username}

server:
  port: 8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true

app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:3001
      - http://127.0.0.1:3000
      - http://127.0.0.1:3001
    allowed-methods:
      - GET
      - POST
      - PUT
      - PATCH
      - DELETE
      - OPTIONS
    allowed-headers:
      - "*"
    exposed-headers:
      - Authorization
    allow-credentials: true
