spring:
  application:
    name: identity-service

  datasource:
    url: jdbc:postgresql://localhost:5432/iiiotwms
    username: postgres
    password: psd@1185

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    enabled: true
